services:
  web:
    image: ilhamtahir/proto-hub-frontend:main
    volumes:
      - ./nginx/sites:/etc/nginx/templates
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    env_file:
      - ./.env
  backend:
    image: ilhamtahir/proto-hub-service:main
    ports:
      - "8082:80"
    volumes:
      - ./data:/data
    env_file:
      - ./.env
